import type { Metadata } from "next";
import { Open_Sans, Montserrat } from "next/font/google";
import "./globals.css";
import { CartProvider } from '@/components/CartContext';
import { OrderHistoryProvider } from '@/components/OrderHistoryContext';
import { Providers } from "@/app/providers";

const openSans = Open_Sans({ 
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-open-sans"
});

const montserrat = Montserrat({ 
  subsets: ["latin"],
  weight: ["100", "300", "400"],
  variable: "--font-montserrat"
});

export const metadata: Metadata = {
  title: "Uomo Migliore",
  description: "A Next.js project automatically generated by Anima",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
      <CartProvider>
        <OrderHistoryProvider>
        {children}
        </OrderHistoryProvider>
      </CartProvider>
      </Providers>
      </body>
    </html>
  );
}
